### ISSUE TITLE
Do noe know which reference should be choosen for doing blast

### ISSUE THREAD

**Issue by houruiyan** [atarashansky/SAMap#101]
Hi , Thank you for your reply. 
Actually I still cannot understand last question.   I have the single cell h5ad file. The gene var index looks like this. But I do not know which reference genome I should select to do the blast. 
![image](https://user-images.githubusercontent.com/56068158/209507223-da04f9b4-f41c-4b56-af9d-fde12b5533df.png)

Could you tell me ? Which reference sequence should I select then I do not need to do some combination? 
http://asia.ensembl.org/info/data/ftp/index.html/
![image](https://user-images.githubusercontent.com/56068158/209507332-e53ee7c2-36da-4037-a737-4f2532e3155a.png)

Thank you! 
https://github.com/atarashansky/SAMap/issues/97 This question did not be solved. Because even if I drop the .1 .2 , they still cannot match. For example, for human , the gene is ENSG_    , the isoform is ENST_  

Hope to get your answer. Thank you very much!

Ruiyan

**Comment by atarashansky** [comment]
Ah, got it. You want CDS (FASTA), most likely.

**Comment by houruiyan** [comment]
Hello Alec, I found the CDS (FASTA）also include some sequence transcript level rather than gene level. So is it reliable if I just average different transcript value for one gene by using the transform table between gene_id and transcript_id?

**Comment by atarashansky** [comment]
This is a parameter to the SAMAP class:
<img width="995" alt="Screen Shot 2022-12-28 at 11 28 07 AM" src="https://user-images.githubusercontent.com/16548075/209842770-db649ef4-a5cf-47e8-85a9-ba8f6087e087.png">

It looks like:
`names = {'mo': mo_mapping, 'hu': hu_mapping, ... }`

`mo_mapping` can be a list of tuples mapping each fasta header to its corresponding gene ID in your dataset.
`[(fasta_id1, gene_id1),(fasta_id2, gene_id2),...]`

That should be exactly what you need.

**Comment by atarashansky** [comment]
Closing for now, please reopen if you still have questions!

**Comment by LalicJ** [comment]
@atarashansky Sorry to bother you! I met the same error! My file gene names start with `ENSMFAG`, but the result of BLAST starts with `ENSMFAT`. Where and how can I modify them? Change the BLAST file or change the adata.var?  I'd appreciate any help getting past this! 
Hope to get your answer. Thank you very much!

**Comment by atarashansky** [comment]
Check out my comment above yours! That parameter is what you need.

**Comment by LalicJ** [comment]
Yes, I understand your answer above, but I would like to ask if there is a faster way to match them one by one? Because I can't think of a good way to match them up(poor coding ability...
sorry to bother you again. I'd appreciate any help getting past this! Thanks!
