### ISSUE TITLE
transfer_annotations - removed

### ISSUE THREAD

**Issue by kullrich** [atarashansky/SAMap#104]
Hi,

in the original vignette, there was the function `transfer_annotations`.

This function is not there anymore in the analysis.py file.

Could you please explain, why you removed the function, is it still valid to use it as it was in the older versions or what are the problems with it?

Thank you in anticipation

Best regards

Kristian

**Comment by kullrich** [comment]
Should be this commit:

https://github.com/atarashansky/SAMap/commit/a2b28391285c8688ccf986efff5358b8060b7cc7

```
# TODO: Deprecate for now and fix this later
def transfer_annotations(sm,reference_id=None, keys=[],num_iters=5, inplace = True):
```

**Comment by atarashansky** [comment]
Hi Kristian - I deprecated and removed this function because the quality of the label propagation was never thoroughly evaluated (this particular functionality was not used in the publication). There may not necessarily be a problem with it as the methodology is inspired by the approach taken by [Conos](https://www.nature.com/articles/s41592-019-0466-z). If you'd still like to use this function, feel free to do so externally.

**Comment by kullrich** [comment]
OK, I really like this functionality, since I am working with some pre-annotated data sets and transfering the cell types directly with SAMap is a very good feature in my opinion.

Another question would be if you ever tested integrating two data sets from the same species with SAMap?

I tested and so far it looks quite promising to me.

Thank you in anticipation

Best regards

Kristian

**Comment by dnjst** [comment]
I will second that transfer_annotations was very useful.

@tarashansky and @kullrich, could you explain briefly how you integrate from the same species with SAMap? Do you give each different species keys, and build a BLAST graph of the same FASTA to itself?

**Comment by atarashansky** [comment]
Hi @dnjst - sorry for the late reply. You can use the (unfortunately undocumented) `_mapper` function in the samap module (from samap import _mapper). This function is the core mapping engine that aligns the manifolds together.

The required input is `sams`: a dictionary of dataset ID as keys (e.g. `dataset1` and `dataset2`) and corresponding SAM objects as values.

That's all you need. `_mapper` will align them and spit out a combined SAM object. So, for example, you would run:
`combined_sam = _mapper(sams, umap=True)`

**Comment by atarashansky** [comment]
Another useful use case for SAMAP is to align datasets from the same species that have been mapped to different transcriptomes. In that case, you would treat them as separate species and run the analysis in the exact way you would run it for mapping two different species.

**Comment by atarashansky** [comment]
(Closing this issue for now, if you have any more questions please reopen!!)
