### ISSUE TITLE
How to use appropriate single cell data files as input files for SAMap correctly？

### ISSUE THREAD

**Issue by HYJ-hh** [atarashansky/SAMap#113]
Hello,

I noticed that "SAMap accepts file paths to unprocessed, raw .h5ad files. The only processing that should be done on these files is to remove low-quality cells. Otherwise, they should be completely unprocessed. ”

this means that， I should use a unprocessed, raw .h5ad files with non-normalized count matrix？

**Comment by atarashansky** [comment]
Correct!
