### ISSUE TITLE
The gene expression levels after SAMap-integrated  are all greater than 0 

### ISSUE THREAD

**Issue by HYJ-hh** [atarashansky/SAMap#116]
Hello,
      I noticed that after integration with SAMap, the gene expression levels are all greater than 1, which is usually greater than 0, I can't find a specific reason.

**Comment by atarashansky** [comment]
Hello, nice observation. If you processed the data with SAM (e.g. loaded raw h5ad's into SAMAP), then that's why. SAM preprocessing function zeroes out expressions less than 1 by default.

**Comment by HYJ-hh** [comment]
Thank you. In that case, perhaps I should go and learn more about SAM.
