### ISSUE TITLE
ModuleNotFoundError: No module named 'samalg'

### ISSUE THREAD

**Issue by DinithiRajapaksha** [atarashansky/SAMap#120]
Hi,
I get the following error. I have installed SAMap following the vignette. Can you please help me to resolve this issue

ModuleNotFoundError Traceback (most recent call last)
Cell In[1], line 1
----> 1 from samap.mapping import SAMAP
2 from samap.analysis import (get_mapping_scores, GenePairFinder,
3 sankey_plot, chord_plot, CellTypeTriangles,
4 ParalogSubstitutions, FunctionalEnrichment,
5 convert_eggnog_to_homologs, GeneTriangles)
6 from samalg import SAM

File ~\samap_directory\samap_init_.py:4
2 import scipy as sp
3 import numpy as np
----> 4 import samalg.utilities as ut
5 import warnings
6 import scanpy as sc

ModuleNotFoundError: No module named 'samalg'

**Comment by atarashansky** [comment]
Try running `pip install sam-algorithm`

**Comment by DinithiRajapaksha** [comment]
Thank you very much.

Kind regards,
Dinithi Rajapaksha
