### ISSUE TITLE
Could alternative methods for BLAST be used?

### ISSUE THREAD

**Issue by Budjavac** [atarashansky/SAMap#138]
I was wondering if there was a way of incorporating an alternative BLAST method into this pipeline.
E.g. would it be possible to, instead of using the map_genes.sh command to perform BLAST between each pair of transcriptomes or proteomes via running a DIAMOND alignment via orthofinder?

**Comment by atarashansky** [comment]
As long as you can generate a homology graph, then any mapper can be used. There's an optional parameter to the SAMAP(...) constructor called `gnnm` which accepts a custom homology graph. The docstring is a bit out of date, but it's a tuple of (homology_graph, genes, gene_species_dictionary):
 - `homology_graph` is a scipy sparse adjacency matrix with edges connecting mapped genes.
 - `genes` is a numpy array of genes corresponding to each row/col of the homology graph
 - `gene_species_dictionary` is a `dict` with species IDs as keys and their respective genes (stored as numpy arrays) as values.
Passing this in will override SAMAP's requirement to have the BLAST output available.

**Comment by Budjavac** [comment]
Thank you!
Closing the thread
