### ISSUE TITLE
Gene filtering parameter

### ISSUE THREAD

**Issue by dariotommasini** [atarashansky/SAMap#139]
Hi @atarashansky , 

I noticed in the paper that "genes expressed in greater than 96% of cells are filtered out." Is there a way to modify this? 

Thanks!
Dario

**Comment by atarashansky** [comment]
This is a preprocessing parameter hardcoded to 0.96 and passed into `SAM.preprocess_data`.
You can either clone the repo to your machine, change the 0.96 to something else, and `pip install .` in the root directory of the repo, or you can run SAM yourself and then pass the SAM objects into SAMAP directly.

**Comment by atarashansky** [comment]
Yeah, that's right!
