### ISSUE TITLE
PyPi package?

### ISSUE THREAD

**Issue by pinin4fjords** [atarashansky/SAMap#16]
Hi - thanks for your work on this, I'm trying it out now. 

Integration in our workflows would be easier if there were a Bioconda package (which would also provide you with a container you don't have to maintain), which I'm happy to do for you. That's easier if there's already a PyPi package- are you planning to do that? If not I can make a Bioconda package directly from here, but I'd need a tagged release at least (e.g. 'v0.1.4') to provide a static .tar.gz, so maybe you could make one of those?

Jon

**Comment by atarashansky** [comment]
Hi, Jon! 

Thanks for the offer! That would be much appreciated. I just released SAMap on PyPi (`pip install samap`). Let me know if you have any questions about the analysis.
-Alec

**Comment by pinin4fjords** [comment]
I'm not actually seeing on PyPi when I search, is it maybe private?

If it's helpful, this is the GitHub actions pattern we use for our Python packages: https://github.com/ebi-gene-expression-group/scanpy-scripts/blob/develop/.github/workflows/python-package-release.yml. With the correct secrets configured etc it causes creates a new PyPi release every time we release on GitHub. Then we put a Conda wrapper around the PyPi.

**Comment by atarashansky** [comment]
It's not showing up for me either when I search, maybe because I released it 15 minutes ago?

Does this link work? https://pypi.org/project/samap/

**Comment by pinin4fjords** [comment]
Ahh yep, that's it, thanks.

**Comment by pinin4fjords** [comment]
Ok done, see: https://github.com/bioconda/bioconda-recipes/pull/26736, and also https://github.com/bioconda/bioconda-recipes/pull/26735. Should be conda channeslContainers at:

- SAM algorithm: https://github.com/bioconda/bioconda-recipes/pull/26735 - https://quay.io/repository/biocontainers/sam-algorithm - https://quay.io/repository/biocontainers/sam-algorithm
- SAMap: https://github.com/bioconda/bioconda-recipes/pull/26736 - https://anaconda.org/bioconda/samap - https://quay.io/repository/biocontainers/samap

**Comment by pinin4fjords** [comment]
Hmm, currently not working, something to do with hnswlib on Conda. Working to resolve...

**Comment by pinin4fjords** [comment]
all good https://github.com/bioconda/bioconda-recipes/pull/26749

**Comment by atarashansky** [comment]
Thank you for getting SAM and SAMap onto Bioconda! It makes my build system a bit easier as well. 

I'm not too familiar with how conda packages work. Do the Bioconda packages automatically pull the latest version from pip or do new versions on pip have to be manually repackaged into an updated conda package?

**Comment by pinin4fjords** [comment]
No worries :-)

It picks it up from PyPi, the Bioconda CI will make a new build for every PyPi releases, someone just has to approve it each time and issue a command to merge a PR (assuming nothing goes wrong with the build). I've added you as a maintainer so you'll get the pings, but I'll keep an eye too.

As mentioned above, we find it easiest to manage releases on GitHub and have the CI (via GitHub actions) do the PyPi release automatically, which then creates the Bioconda release.
