### ISSUE TITLE
ScanPy/UMAP compatibility

### ISSUE THREAD

**Issue by wagnerde** [atarashansky/SAMap#32]
By default installing SAMap will install the latest version of ScanPy (1.7.1), which is now configured for compatibility with the newest version of UMAP (0.5).  However, SAMap appears to require UMAP 0.4.6.  I experienced a few potential problems with (new) ScanPy passing arguments to (old) UMAP, e.g:

Running UMAP on the stitched manifolds.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-7f6f78087d82> in <module>()
      7 # runs SAMAP
      8 sm = SAMAP(fn1,fn2,id1,id2,f_maps = '/content/maps/')
----> 9 samap = sm.run()

2 frames
/usr/local/lib/python3.7/dist-packages/scanpy/tools/_umap.py in simplicial_set_embedding(*args, **kwargs)
    147                 densmap_kwds={},
    148                 output_dens=False,
--> 149                 **kwargs,
    150             )
    151             return X_umap

TypeError: simplicial_set_embedding() got an unexpected keyword argument 'densmap'

Using the previous version of ScanPy (1.6.0) seems to have resolved this issue.

**Comment by atarashansky** [comment]
Thanks for letting me know scanpy updated to use the newest version of UMAP. I pinned UMAP to be <0.5 but seems like I can unpin it now!
