### ISSUE TITLE
Would you add some example data for test?

### ISSUE THREAD

**Issue by yxj17173** [atarashansky/SAMap#34]
Such as a subset of datasets “media/storage/Dropbox/scrna/notebooks/data/planarian.h5ad” and "media/storage/Dropbox/blasting/planarian_transcriptome.fasta“. That could be much more convenient. Thanks

**Comment by atarashansky** [comment]
I'll work on getting some small datasets uploaded that can be used to test the pipeline!

**Comment by yxj17173** [comment]
> I'll work on getting some small datasets uploaded that can be used to test the pipeline!

That's great!

**Comment by atarashansky** [comment]
Done!
