### ISSUE TITLE
Segmentation fault running map_genes.sh

### ISSUE THREAD

**Issue by dkeitley** [atarashansky/SAMap#35]
Hi,

I'm currently running into a segmentation fault error when trying to run the `map_genes.sh` script on the following transcriptomes. 

Fasta files:
http://ftp.ensembl.org/pub/release-104/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.toplevel.fa.gz
http://ftp.ensembl.org/pub/release-104/fasta/oryctolagus_cuniculus/dna/Oryctolagus_cuniculus.OryCun2.0.dna.toplevel.fa.gz

Error:
```
map_genes.sh: line 116: 155333 Segmentation fault      tblastx -query $tr1 -db $tr2 -outfmt 6 -out "maps/${n1}${n2}/${n1}_to_${n2}.txt" -num_threads 8 -max_hsps 1 -evalue 1e-6
map_genes.sh: line 116: 87881 Segmentation fault      tblastx -query $tr2 -db $tr1 -outfmt 6 -out "maps/${n1}${n2}/${n2}_to_${n1}.txt" -num_threads 8 -max_hsps 1 -evalue 1e-6
```

Do you have any ideas as to what I might be doing wrong?

Many thanks,

Dan

**Comment by dkeitley** [comment]
Ok so just to clarify, since my data features are given in terms of gene IDs, if I use Ensembl BioMart to get the associated transcript IDs and then pass that to the SAMAP object as a list of tuples, will that be ok? Is it a problem if the mapping passed to SAMAP is not one-to-one (i.e. many fasta transcript IDs will be associated with a single gene ID feature) ?

**Comment by atarashansky** [comment]
Yeah, that should be okay. There's no problem if it's not one-to-one, as SAMap will automatically combine the mapping results of transcripts that correspond to a single gene symbol.
