### ISSUE TITLE
Extracting cross-species nearest neighbours

### ISSUE THREAD

**Issue by dkeitley** [atarashansky/SAMap#38]
Hi,

I was wondering whether it was possible to extract, for each cell, its cross-species nearest neighbours in the final SAMAP or adata object? Is this what the `knn_1v2` matrix in the `mdata` object relates to for example?

Many thanks,

Dan

**Comment by FlameFinance** [comment]
knn1v2 are the nearest neighbors from cells i species 1 to cells in species 2, and these neighbors have not been filtered out based on mutual connectivity. 

If that’s alright with you, then you can use that! You can also use ‘xsim’ which encodes the mutual nearest neighborhoods for each pair of cells across species (there is a strong edge between two cells if their respective neighborhoods have a lot of mutual connectivity in the knn1v2 and knn2v1 graphs).

**Comment by atarashansky** [comment]
knn1v2 are the nearest neighbors from cells i species 1 to cells in species 2, and these neighbors have not been filtered out based on mutual connectivity.

If that’s alright with you, then you can use that! You can also use ‘xsim’ which encodes the mutual nearest neighborhoods for each pair of cells across species (there is a strong edge between two cells if their respective neighborhoods have a lot of mutual connectivity in the knn1v2 and knn2v1 graphs).
