### ISSUE TITLE
SAMap error with windows machines

### ISSUE THREAD

**Issue by jmmusser** [atarashansky/SAMap#51]
Hi Alec,

We are having a consistent problem on all windows machines. We install SAMap and all dependencies successfully in a windows conda environment. However, when we run the third cell in the example jupyter lab notebook, which includes the main SAMap command, we are consistently getting the same error. The error comes after the following output line:

Recomputing PC projections with gene pair subsets...

Here is the error message:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_5400/2860598093.py in <module>
     19 
     20 sm = SAMAP(sam1,sam2,id1,id2,f_maps = 'example_data/maps/')
---> 21 samap = sm.run()
     22 #"""

~\SAMap\samap\mapping.py in run(self, NUMITERS, NH1, NH2, crossK, N_GENE_CHUNKS, umap, ncpus, hom_edge_thr, hom_edge_mode, scale_edges_by_corr, neigh_from_key1, neigh_from_key2)
    350             scale_edges_by_corr = scale_edges_by_corr,
    351             neigh_from_key1=neigh_from_key1,
--> 352             neigh_from_key2=neigh_from_key2
    353         )
    354         samap = smap.final_sam

~\SAMap\samap\mapping.py in run(self, NUMITERS, NOPs1, NOPs2, NH1, NH2, K, corr_mode, NCLUSTERS, scale_edges_by_corr, THR, neigh_from_key1, neigh_from_key2, ncpus)
    685                 scale_edges_by_corr=scale_edges_by_corr,
    686                 neigh_from_key1=neigh_from_key1,
--> 687                 neigh_from_key2=neigh_from_key2
    688             )
    689 

~\SAMap\samap\mapping.py in _mapper(sams, gnnm, gn, NH1, NH2, umap, mdata, k, K, chunksize, coarsen, key1, key2, scale_edges_by_corr, neigh_from_key1, neigh_from_key2, **kwargs)
    774 
    775             if mdata is None:
--> 776                 mdata = _mapping_window(sam, sam2, gnnm, gn, K=K)
    777 
    778             if k is None:

~\SAMap\samap\mapping.py in _mapping_window(sam1, sam2, gnnm, gn, K)
   1938     wpca2 = wpca[s1.shape[0] :, :]
   1939 
-> 1940     b1, b2 = _united_proj(wpca1, wpca2, k=k)
   1941 
   1942     output_dict = {}

~\SAMap\samap\mapping.py in _united_proj(wpca1, wpca2, k, metric, sigma, ef, M)
   1859     x1 = np.tile(np.arange(idx1.shape[0])[:, None], (1, idx1.shape[1])).flatten()
   1860     x2 = np.tile(np.arange(idx2.shape[0])[:, None], (1, idx2.shape[1])).flatten()
-> 1861     knn1v2[x1, idx1.flatten()] = Sim1.flatten()
   1862     knn2v1[x2, idx2.flatten()] = Sim2.flatten()
   1863 

~\Miniconda3\envs\SAMap2\lib\site-packages\scipy\sparse\lil.py in __setitem__(self, key, x)
    331             return self._set_intXint(key[0], key[1], x)
    332         # Everything else takes the normal path.
--> 333         IndexMixin.__setitem__(self, key, x)
    334 
    335     def _mul_scalar(self, other):

~\Miniconda3\envs\SAMap2\lib\site-packages\scipy\sparse\_index.py in __setitem__(self, key, x)
    123                 return
    124             x = x.reshape(i.shape)
--> 125             self._set_arrayXarray(i, j, x)
    126 
    127     def _validate_indices(self, key):

~\Miniconda3\envs\SAMap2\lib\site-packages\scipy\sparse\lil.py in _set_arrayXarray(self, row, col, x)
    305         _csparsetools.lil_fancy_set(self.shape[0], self.shape[1],
    306                                     self.rows, self.data,
--> 307                                     i, j, x)
    308 
    309     def _set_arrayXarray_sparse(self, row, col, x):

_csparsetools.pyx in scipy.sparse._csparsetools.lil_fancy_set()

_csparsetools.pyx in scipy.sparse._csparsetools._lil_fancy_set_int32_longdouble()

ValueError: Buffer dtype mismatch, expected 'npy_int32' but got 'long long'

**Comment by atarashansky** [comment]
Hi Jake,

seems like this is a known incompatibility with windows. I’ll look into a fix, although it’ll be a bit tricky to debug since I don’t have a windows computer. 

I might suggest trying the docker image in the meantime.

**Comment by muss0044** [comment]
Hi Alec,

Thanks for letting me know. I suspected something like this. I am going 
to test another option tonight, which is to save the final SAMAP object 
and just give it to the windows users.

A couple windows users tried Docker but they both ran into the issue 
that the python kernal kept dying in the first few commands. I 
originally had this problem too when I tested it out on my windows 
machine at home, but it somehow resolved itself after a few days (very 
odd, not sure how it just solved itself).

Lastly, I also had a problem with samgui on one of the windows machine. 
I installed jupyter lab v3.0.7 and used your instructions to install the 
widgets. The installation commands worked as long as I took out the 
version numbers (i.e. deleted @1.0.0), as you suggested. However, when I 
loaded the planarian sam object and ran the gui, only the menu/options 
part of the gui loaded, without showing the side of the gui with the 
plots. Have you seen this before?

Jake

atarashansky wrote on 09/09/2021 19:10:

**Comment by atarashansky** [comment]
Regarding the docker - I think it's `hnswlib` that causes the crash.
Because it uses C libraries, which have to be compiled differently
depending on the OS. I'm not sure how to fix it for windows.

Regarding the SAMGUI, that issue is a known incompatibility with Jupyter
lab that should have been resolved with the instructions you followed. I'm
not sure how to fix it for Windows yet. In the meantime, you guys can use
Jupyter notebook instead. Jupyter notebook should have no issues regardless
of what platform it's on.

Why does maintaining a software package across operating systems have to be
such a nightmare, lol...

Best,
Alec

**Comment by atarashansky** [comment]
Fixed on the main branch on github. The fix will be included on the next pip release - for now, please install from source by:

```
git clone https://github.com/atarashansky/SAMap
cd SAMap
pip install .
```

Best,
Alec
