### ISSUE TITLE
Updating transcript ids using names1 and names2

### ISSUE THREAD

**Issue by kmmika** [atarashansky/SAMap#54]
Hello! I've run through SAMap and realized that the program grabbed the Ensembl transcript ids instead of the gene symbols from the fasta files and this had made interpreting the results difficult. I found the names parameter in the mapping.py documentation and it seemed like it could do exactly what I needed. However, I keep getting the below error. I've checked with a labmate to make sure I'm just not messing up basic python (very possible- I usually work in R) but we can't seem to solve the error. I'd appreciate any help getting past this! Thanks!

```
from samap.mapping import SAMAP
from samap.analysis import (get_mapping_scores, GenePairFinder, transfer_annotations,
                            sankey_plot, chord_plot, CellTypeTriangles, 
                            ParalogSubstitutions, FunctionalEnrichment,
                            convert_eggnog_to_homologs, GeneTriangles)
from samalg import SAM

fn1 = 'zf_merge_forSAMap.h5ad'
fn2 = 'mouse_forSAMap.h5ad'

filenames = {'zf':fn1,'mm':fn2}

names1 = 'zf_nms.tsv'
names2 = 'mm_nms.tsv'

sams = {'zf':fn1,'mm':fn2}

sm = SAMAP(sams, f_maps = 'maps/', names = [names1, names2])

Processing data zf from:
zf_merge_forSAMap.h5ad
RUNNING SAM
Iteration: 0, Convergence: 1.0
Iteration: 1, Convergence: 0.8680947121481865
Iteration: 2, Convergence: 0.01547177003310972
Computing the UMAP embedding...
Elapsed time: 225.89533114433289 seconds
Not updating the manifold...
Processing data mm from:
mouse_forSAMap.h5ad
RUNNING SAM
Iteration: 0, Convergence: 1.0
Iteration: 1, Convergence: 0.705245355298752
Iteration: 2, Convergence: 0.054249228157205155
Computing the UMAP embedding...
Elapsed time: 152.4312560558319 seconds
Not updating the manifold...
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-17-cb6e3de84f40> in <module>
      1 sams = {'zf':fn1,'mm':fn2}
      2 
----> 3 sm = SAMAP(sams, f_maps = 'maps/', names = [names1, names2])

/usr/local/anaconda3/lib/python3.8/site-packages/samap/mapping.py in __init__(self, sams, f_maps, names, keys, resolutions, gnnm, save_processed)
    163             if names is not None:
    164                 gnnm, gns, gns_dict  = _coarsen_blast_graph(
--> 165                     gnnm, gns_list, gns, ids, names
    166                 )
    167 

UnboundLocalError: local variable 'gns_list' referenced before assignment
```

**Comment by atarashansky** [comment]
Ahh, thanks for reminding me. I still need to update that functionality in the latest version. I'll fix it today! Meanwhile, you could try downgrading to v0.2.3. Note that the input/output for SAMap is structured a bit differently so please refer to `SAMap_quickstart.ipynb` for guidance if you decide to downgrade while I fix this issue. https://github.com/atarashansky/SAMap/tree/v0.2.3

I'll ping you once it's ready!

**Comment by atarashansky** [comment]
Also, `names1` and `names2` should be an Nx2 numpy array (or a list of tuples) so you'll have to load the csv files first and pass in the result directly. I'll provide a detailed example here for guidance after fixing the issue in v0.3.0.

**Comment by kmmika** [comment]
Wonderful, thank you on both fronts! I'm not in a rush so I can definitely wait a bit. I appreciate the update/guidance!

**Comment by atarashansky** [comment]
Alright, I think I got it working. It should be ready to roll in v0.3.1.

Upgrade with: `pip install samap==0.3.1`
To use, please prepare a list of tuples or a 2D numpy array for each species you want to translate.

For example:
```python

# assuming we want to translate human species with ID 'hu'
n1 = [('ENSG30000001','Gene1'),('ENSG30000002','Gene2')]
# n1 could also be n1 = np.array([['ENSG30000001','Gene1')],['ENSG30000002','Gene2']])
names = {'hu':n1} 

sm = SAMAP(sams, f_maps = 'maps/', names =names)
```

I didn't get a chance to test this that thoroughly, so hopefully it works, lol. Please let me know if you're still having trouble.

**Comment by atarashansky** [comment]
Just tested it with an example on my end and it works :). Closing now, but feel free to reopen if there are any outstanding issues.
