### ISSUE TITLE
Calculate Mapping Scores with leiden_clusters

### ISSUE THREAD

**Issue by kmmika** [atarashansky/SAMap#55]
Hello again! I am trying to calculate mapping scores using leiden_clusters and keep getting the following error. I get the same error when I set both zf and mm to 'leiden_clusters'. Everything works fine if I use batch or cell type instead of leiden_clusters. I have tried creating a whole new column with a different dtype to see if that solved the issue and get a KeyError instead. Any help is appreciated, thanks!

keys = {'zf':'leiden_clusters','mm':'cell_type'}
D,MappingTable = get_mapping_scores(sm,keys,n_top = 100)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-107-5d45a43ac4e1> in <module>
      1 keys = {'zf':'leiden_clusters','mm':'cell_type'}
----> 2 D,MappingTable = get_mapping_scores(sm,keys,n_top = 100)

/usr/local/anaconda3/lib/python3.8/site-packages/samap/analysis.py in get_mapping_scores(sm, keys, n_top)
   1563 
   1564     for sid in skeys:
-> 1565         clusters.append(q([sid+'_'+x for x in sm.sams[sid].adata.obs[keys[sid]]]))
   1566 
   1567     cl = np.concatenate(clusters)

/usr/local/anaconda3/lib/python3.8/site-packages/samap/analysis.py in <listcomp>(.0)
   1563 
   1564     for sid in skeys:
-> 1565         clusters.append(q([sid+'_'+x for x in sm.sams[sid].adata.obs[keys[sid]]]))
   1566 
   1567     cl = np.concatenate(clusters)

TypeError: can only concatenate str (not "int") to str

**Comment by kmmika** [comment]
Happy to help, lol. Thank you so much for responding so quickly!! That worked perfectly.

**Comment by atarashansky** [comment]
Fixed in v0.3.2!
