### ISSUE TITLE
Jupyter Notebook launched from docker container crashes when importing SAMap

### ISSUE THREAD

**Issue by JesseDGibson** [atarashansky/SAMap#63]
Hey Alec, it seems like the installation in the docker container at `tarashan/samap:latest` crashes when importing SAMap. I set it up by running 

      docker pull tarashan/samap:latest
      chmod 777 ~/data/
      docker run -it --rm -v ~/data/:/jupyter/notebooks -p 8080:8080 -e PORT=8080 tarashan/samap:latest

In the Jupyter Lab instance this launched, I tried the following import statements which run fine as written but kills the kernel if I un-comment the line importing SAMap

      import anndata
      import matplotlib
      import matplotlib.pyplot as plt
      import numpy as np
      import pandas as pd
      import scanpy as sc
      import re
      from samalg import SAM
      ### This is the buggy import ###
      # from samap.mapping import SAMAP
      ################################
      from samalg.gui import SAMGUI
      from samap.analysis import (get_mapping_scores, GenePairFinder, transfer_annotations,
                                  sankey_plot, chord_plot, CellTypeTriangles, 
                                  ParalogSubstitutions, FunctionalEnrichment,
                                  convert_eggnog_to_homologs, GeneTriangles)

      matplotlib.rcParams.update({'font.size': 12})
      %config InlineBackend.figure_format = 'retina'`

I initially tried this on someone's Macbook with something like 4 cores and 16ish GB of RAM so thought it might be a memory issue, but we run into the same issue on a GPC instance with 32 cores and ~200 GB RAM so I'm skeptical that memory is the problem there. Have you been able to run a jupyter notebook and import SAMap from the container? Any advice? Thanks!

**Comment by atarashansky** [comment]
Hey, Jesse. Sorry about the delay.

I've seen this bug before when importing `hnswlib` (a dependency in SAMAP) in the docker container but it's been virtually impossible to reliably reproduce.

I'll look into this and get back to you.

**Comment by JesseDGibson** [comment]
Hey Alec, no worries. For reference, if I use the Dockerfile below that just pip installs from the github, it does build an image that lets me at least import SAMap without bugs. Probably not the most memory efficient and needs to be stress tested to make sure all of the parts of SAMap actually run, but it seems to do the job

      FROM debian:buster-slim
      RUN echo "Reset"
      ARG PATH="/scratch/miniconda/bin:${PATH}"
      ENV PATH="/scratch/miniconda/bin:${PATH}"
      
      RUN apt-get update \
          && apt-get install -y wget \
          && apt-get install -y g++ \ 
          && apt-get install -y build-essential \
          && apt-get install -y git \ 
          && apt-get install -y libcurl4-gnutls-dev libxml2-dev libssl-dev
              
      RUN wget -O /tmp/miniconda.sh \
          https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
              
      RUN bash /tmp/miniconda.sh -b -p /scratch/miniconda \
          && rm -f /tmp/miniconda.sh \
          && conda install -y -c conda-forge python=3.7 pip pybind11 h5py=2.10.0 leidenalg python-igraph texttable jupyterlab \
          && pip install git+https://github.com/eggnogdb/eggnog-mapper.git \
          && git clone https://github.com/atarashansky/SAMap.git /scratch/SAMap/ \
          && cd /scratch/SAMap \ 
          && pip install . \
          && cd /scratch/ 
      
      RUN wget "ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast-2.9.0+-x64-linux.tar.gz" \ 
          && tar -xzvf "ncbi-blast-2.9.0+-x64-linux.tar.gz" \
                 -C "/scratch/miniconda/bin/" \
                 --strip-components=2 \
                 "ncbi-blast-2.9.0+/bin/"
      
      WORKDIR /scratch/
      
      CMD jupyter lab --port=$PORT --no-browser --allow-root --ip=0.0.0.0 --NotebookApp.password="" --NotebookApp.token=""

**Comment by atarashansky** [comment]
Deprecating docker support for now as it's too flakey without significant overhaul...
