### ISSUE TITLE
Usage of map_genes.sh

### ISSUE THREAD

**Issue by PeiwenJi** [atarashansky/SAMap#64]
I am trying to run map_genes.sh, but I don't know how it works.

I have installed NCBI BLAST version 2.9.0, but I get an error when running 
bash map_genes.sh 'mydata/sa.fna' 'nucl' 'sa' 'mydata/sp.fasta' 'nucl' 'sp' 
Error: (CArgException::eNoArg) Argument "dbtype". Mandatory value is missing: `String, `nucl', `prot'' .

I don't know what to do.

**Comment by atarashansky** [comment]
Check out the vignette (the snippet isn't displaying in github for some reason, so you must open the jupyter notebook on your computer)

https://github.com/atarashansky/SAMap/blob/main/SAMap_vignette.ipynb

Specifically, here's the snippet:

```python
file1 = 'example_data/transcriptomes/schistosome_proteome.fasta'
type1 = 'prot' #or 'prot' if file1 is a proteome
id1 = 'sc' #2-character ID (e.g. 'sc' for schistosome)

file2 = 'example_data/transcriptomes/planarian_transcriptome.fasta'
type2 = 'nucl'
id2 = 'pl' #2-character ID (e.g. 'pl' for planarian)
!bash map_genes.sh --tr1 {file1} --t1 {type1} --n1 {id1} --tr2 {file2} --t2 {type2} --n2 {id2}
```

To run it from the command-line, the command looks like follows:

`bash map_genes.sh --tr1 {file1} --t1 {type1} --n1 {id1} --tr2 {file2} --t2 {type2} --n2 {id2}`

`bash map_genes.sh --tr1 mydata/sa.fna --t1 nucl --n1 sa --tr2 mydata/sp.fasta --t2 nucl --n2 sp`

**Comment by PeiwenJi** [comment]
已收到您的邮件谢谢~

**Comment by PeiwenJi** [comment]
I solved the problem, thank you very much!!!
