### ISSUE TITLE
`SAMAP()` taking too long to run?

### ISSUE THREAD

**Issue by archavan** [atarashansky/SAMap#67]
I was wondering how long I should expect the `SAMAP()` step to take? In the vignette I see that the `sm.run()` step took about a minute, but I wasn't sure how long the `SAMAP()` step took. 

I am using datasets from two species, amphioxus and human, with ~4,000 and ~18,000 cells respectively, and ~20,000 genes each. When I ran this step, it printed the message (pasted below) that it was finished running SAM on each dataset but then it was still working for hours. I wasn't sure if this step uses multiple CPUs, so I ran it twice -- 1 CPU with 60GB memory  & 25 CPUs with 4GB memory each -- and for both of these runs, this step ran for about 20 hours without printing any further messages (at which point I killed both runs suspecting that something was perhaps wrong).  

I just wanted to make sure whether it's expected for this step to take this long or if there was something I was doing wrong and need to fix? I am of course happy to provide any other information about the datasets etc that would be relevant! Thanks for your time and help!

```
sm = SAMAP(filenames, 
           f_maps = "../results/11_samap_hsap/01_blast/maps/", 
           names = names, 
           keys = keys)
```

```
Processing data bf from:
../results/11_samap_hsap/02_sc-datasets/bf/bf.h5ad
RUNNING SAM
Iteration: 0, Convergence: 1.0
Iteration: 1, Convergence: 0.9121769745265136
Iteration: 2, Convergence: 0.010094183907286473
Computing the UMAP embedding...
Elapsed time: 45.88674068450928 seconds
Not updating the manifold...
Processing data hs from:
../results/11_samap_hsap/02_sc-datasets/hs/fawkner-corbett/hs.h5ad
RUNNING SAM
Iteration: 0, Convergence: 1.0
Iteration: 1, Convergence: 0.8730932242336841
Iteration: 2, Convergence: 0.014479077042175931
Computing the UMAP embedding...
Elapsed time: 86.50676774978638 seconds
Not updating the manifold...
```

**Comment by atarashansky** [comment]
Can you upload your blast tables and send me a link? Seems like the method is hanging on that step.

**Comment by archavan** [comment]
Thanks for looking into it! The blast tables are now on google drive (https://drive.google.com/drive/folders/1RhuNM0DQQdrmSdLuRH9MHSzunAcPzPqi?usp=sharing). Let me know if you need anything else or have trouble accessing the files.

**Comment by atarashansky** [comment]
Hi there, sorry for the delay.

I'm taking a look at this now!

Best,

**Comment by atarashansky** [comment]
Can you also provide the `names` data that you're passing in? I'm going to try the homology graph construction step on my end and see what may be bottlenecking it.

**Comment by atarashansky** [comment]
So there are two computationally intensive steps after processing the data:

1) Construct the homology graph from the BLAST output
2) Coarsen the nodes in the graph based on the mapping provided in `names`. This coarsening is to map the gene nodes in the homology graph to the _gene names_ in your data. Sometimes the BLAST output may include slightly different naming formats, isoforms, etc. For example, `Gene A` in your data may be represented by isoforms `Gene A.1` and `Gene A.2` in your BLAST output. SAMAP will collapse nodes `Gene A.1` and `Gene A.2` into one node `Gene A`.

I just checked step (1) with the BLAST tables, and it took around 1 minute. If there is a bottleneck, it will be in step (2). Once you provide the mapping you used (`names`), I'll be able to debug that step.

Thanks for your patience!

**Comment by archavan** [comment]
Thanks @atarashansky, no rush, please take your time! 

I just put the `names` csvs here: https://drive.google.com/drive/folders/1yJb6XGOx90cYU1roS6tzTCoqfhURzNGr?usp=sharing. 

I then turn them into lists of tuples:
```
names_bf = pd.read_csv(basedir + "results/11_samap_hsap/02_sc-datasets/bf/protein-id-to-gene-id-mapping.csv")
names_hs = pd.read_csv(basedir + "results/11_samap_hsap/02_sc-datasets/hs/fawkner-corbett/protein-id-to-gene-name-mapping.csv")

n1 = list(zip(names_bf["protein_id"], names_bf["gene_id"]))
n2 = list(zip(names_hs["protein_id"], names_hs["gene_symbol"]))
```

**Comment by atarashansky** [comment]
Alright, thanks so much. I think I caught the issue. Long story short, I was trying to find the intersection between two large lists of strings, but the strings were formatted with a really clunky type which made it crazy slow.

Please update samap to version 0.3.5 in your conda environment and try again!
`pip install samap==0.3.5`

It should take ~5-10 minutes in total. Let me know if it's still hanging!

Best,
Alec

**Comment by archavan** [comment]
That fix worked perfectly -- I just tried running it with v0.3.5 and it took about 5 minutes for the `SAMAP()` step to finish running. Thanks so much for your prompt help!

**Comment by YY-SONG0718** [comment]
Hi @atarashansky, I just want to say thank you, I ran into the same issue and the fix worked perfectly :)
