### ISSUE TITLE
after the 'sm.run(pairwise=True)', how to save the results of sm to our disk？

### ISSUE THREAD

**Issue by wubaosheng** [atarashansky/SAMap#71]
after the 'sm.run(pairwise=True)', how to save the results of sm to our disk？ @atarashansky 

![1646528644(1)](https://user-images.githubusercontent.com/50618480/156904835-3a1f5fd2-4bfa-4447-8844-55e73c3fdac5.png)

**Comment by wubaosheng** [comment]
samap.utils.save_samap(sm,'test.sam')
![image](https://user-images.githubusercontent.com/50618480/156907668-529893aa-8201-430e-b6ab-5f7e8d2516a6.png)

**Comment by atarashansky** [comment]
it should be

`samap.utils.save_samap(sm,'test')`

if that doesnt work please save the anndata output by samap: `sm.samap.adata`.
