### ISSUE TITLE
Compute the EggNOG table

### ISSUE THREAD

**Issue by YY-SONG0718** [atarashansky/SAMap#74]
Dear Dr Tarashansky,

Thank you so much for creating this amazing method. I wonder if you could please give a short instruction on how to compute the EggNOG table as in example_data/eggnog? I would like to perform a functional enrichment analysis post-samap.

Kind regards,
Yuyao

**Comment by philoel** [comment]
Hi Yuyao, 

I'm the furthest from an expert possible, but perhaps you are having a similar question I asked a colleague when I started something similar. 

In that case, just submit your proteome(s) to emapper and the output is an eggnog table. You can also run it/compute it your computer if you want to install it and do so. http://eggnog-mapper.embl.de/ 

Maybe that helps :) 
Phil

**Comment by YY-SONG0718** [comment]
> Hi Yuyao,
> 
> I'm the furthest from an expert possible, but perhaps you are having a similar question I asked a colleague when I started something similar.
> 
> In that case, just submit your proteome(s) to emapper and the output is an eggnog table. You can also run it/compute it your computer if you want to install it and do so. http://eggnog-mapper.embl.de/
> 
> Maybe that helps :) Phil

Hi Phil,

Thank you so much for your kind response, this is very helpful! :)

Best regards,
Yuyao
