### ISSUE TITLE
"Too many values to unpack" in sm.run()

### ISSUE THREAD

**Issue by philoel** [atarashansky/SAMap#75]
Hi Alec,

I'm trying to use my cell type labels in sm.run(), using the following bit of code adapted from the example vignette.

```
sm = SAMAP(
        sams,
        f_maps = './maps/',
        keys = {'ad':'adjusted_annotations_20220408','jp':'annotations_20220509'},
    )
sm.run(neigh_from_keys = {'ad':True,'jp':True})
```

It seems to get to the point of concatenating the SAM objects then fails with "too many values to unpack". I'm not a python user so I stink at understanding what the error messages try to tell me. I'm attaching a screenshot of the chunk, and a .txt with the code and its error message in it. 

Any tips? 

While I was scratching my head, I ran sm.run() a different way, a way included a little further up in the vignette, hoping it would at least give me an object I could explore with the Post-SAMap tools in the vignette. I ran

```
sam1=SAM()
sam1.load_data('./pmar_adret-tidy_pr.h5ad')

sam2=SAM()
sam2.load_data('./pmar_ammocoete_retina-sn_pr.h5ad')

sam3=SAM()
sam3.load_data('./pmar_pineal_pr.h5ad')

sams = {'ad':sam1,'jp':sam3}

sm = SAMAP(
        sams,
        f_maps = './maps/',
    )

sm.run(pairwise=True)
```

... and it did seem to run to completion, with no error message and finishing with a "Elapsed time: 3.xxxx minutes" message. However, when I tried to run the Post-SAMap code cells such as 

```
keys = {'ad':'adjusted_annotations_20220408','jp':'annotations_20220509'}
D,MappingTable = get_mapping_scores(sm,keys,n_top = 100)
```

or even 

```
#keys = {'ad':'adjusted_annotations_20220408','jp':'annotations_20220509'}
D,MappingTable = get_mapping_scores(sm,keys,n_top = 100)
```

, I got the same error: "too many values to unpack". 

Seems like I'm stuck here! 

Thanks for any pointers,
Phil
[too_many_values_to_unpack_from_sm-run.txt](https://github.com/atarashansky/SAMap/files/8667522/too_many_values_to_unpack_from_sm-run.txt)
![Screenshot_too_many_values_to_unpack_from_get-mapping-scores](https://user-images.githubusercontent.com/46672796/167790447-e695e51c-8efe-43e8-a18a-21b21b0416a5.png)
![Screenshot_too_many_values_to_unpack_from_sm-run](https://user-images.githubusercontent.com/46672796/167790455-e479df2b-ea6a-40ab-ae0b-78f471375af7.png)

**Comment by atarashansky** [comment]
Hey Phil, it looks like a fresh bug with the alignment score calculation. I’ll fix this ASAP and let you know when/how to update your version.

thanks for catching this and sorry for the inconvenience!

**Comment by philoel** [comment]
Hi Alex, thanks for looking at it so quickly!

For your first comment, I've attached a .txt with the outputs you requested. The four things you asked me to print are preceded by comment signs # to help you browse them faster. 

I can see already that the two objects (ad, jp) seem to react differently to similar commands, so I guess the problem is on my end. I'd be happy for any tips on how to fix them, since I know nothing about python! I can confirm that the annotations that were printed are the correct ones, at least. 

[tester_code_from_AT_for_adjp-samap.txt](https://github.com/atarashansky/SAMap/files/8675711/tester_code_from_AT_for_adjp-samap.txt)

**Comment by philoel** [comment]
And, I can confirm that the example data ran well up to and including the step you provided, and then I was also able to work with the outputs using a few randomly chosen code cells provided in the post-SAMap section (ie I can make mapping table, which I couldn't do with my own data; also a sm.scatter() worked, and I could find gene pairs).

**Comment by philoel** [comment]
>Hey Phil - Having trouble reproducing the issue. Could you print out sm.sams['ad'].obs['adjusted_annotations_20220408'] and sm.sams['jp'].adata.obs['annoations_20220509'] for me?

I just noticed that the first command you asked for, which in my attachment from a few minutes ago gave an error "no attribute obs found", might have had a typo. Specifically:

Original:
> sm.sams['ad'].obs['adjusted_annotations_20220408']

Possibly what was intended?:
>sm.sams['ad'].adata.obs['adjusted_annotations_20220408']

When I change the command to what I think might have been the intended command (including .adata.obs), then I get output, which is the following:

>N160_AAACCCAAGTGCTACT    AC | GABAergic | PTH1R+_likely_subtypes_includ...
SN160_AAACCCAGTCCACTTC                         PR | Cones | Red-cone_opsin+
SN160_AAACCCAGTGCAGATG                       AC | Glycinergic | ZNF804A+, 1
SN160_AAACCCATCCCGTGTT                            BPC | ISL1+ | <undefined>
SN160_AAACCCATCGGTGCAC                   AC | Glycinergic | ZNF804A+_VIPR1+
                                                ...                        
SN178_TTTGTTGGTTGCATAC                    HC | Axon-free | ISL+_SOXB1+_GAD+
SN178_TTTGTTGTCAAGTCGT                BPC | LHX34+ | SALL1+_SALL3+_Otx.pig+
SN178_TTTGTTGTCCGGCTTT                         PR | Cones | Red-cone_opsin+
SN178_TTTGTTGTCGCACGAC                               PR | Rods | Rod_opsin+
SN178_TTTGTTGTCTGAGAGG                                  BPC | ISL1+ | IRX2+
Name: adjusted_annotations_20220408, Length: 13903, dtype: category
Categories (51, object): ['Nonneural | Immune | GATA3+', 'Nonneural | Fibroblast | SIX2+', 'Nonneural | Microglia | KIT+', 'Nonneural | Vascular | VWF+', ..., 'AC | GABAergic | NOS.a+', 'AC | GABAergic | Likely_subtypes', 'AC | GABAergic | <indistinct>', 'AC | GABAergic | Melanopsin+']

**Comment by philoel** [comment]
Hi Alex,

Here are two annotation .txt files; the header is "annotation" of course. 

And, 

I ran the following code:
```
# Alex asked me to give this code a try
sm = SAMAP(
        sams,
        f_maps = './maps/',
        keys = None,
    )
sm.run()
```

I've attached the direct output of that cell of code as "results_of_key=none.txt"; also, I used a selection of follow-up 'Post-SAMap' cell code to get a sense of whether things are improved. sm.scatter() worked as it did at the start of this thread; I could not get a mapping table, since when I passed

```
keys = {'ad':'adjusted_annotations_20220408','jp':'annotations_20220509'}
D,MappingTable = get_mapping_scores(sm,keys,n_top = 0)
```

I got 

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> /scratch/jobs/40359230/ipykernel_46624/1260223800.py in <module>
>       1 keys = {'ad':'adjusted_annotations_20220408','jp':'annotations_20220509'}
> ----> 2 D,MappingTable = get_mapping_scores(sm,keys,n_top = 0)
> 
> /g/arendt/Phil/samap_outs/samap_102/samap_Pmar_adret-amret-juvpineal/samap/analysis.py in get_mapping_scores(sm, keys, n_top)
>    1609     samap.adata.obs[l] = pd.Categorical(cl)
>    1610 
> -> 1611     CSIMth, clu = _compute_csim(samap, l, n_top = n_top, prepend = False)
>    1612 
>    1613     A = pd.DataFrame(data=CSIMth, index=clu, columns=clu)
> 
> /g/arendt/Phil/samap_outs/samap_102/samap_Pmar_adret-amret-juvpineal/samap/analysis.py in _compute_csim(sam3, key, X, prepend, n_top)
>    1474     cell_scores = [valdict[k].sum() for k in valdict.keys()]
>    1475     ixer = pd.Series(data=np.arange(clu.size),index=clu)
> -> 1476     xc,yc = substr(list(valdict.keys()),';')
>    1477     xc = xc.astype('int')
>    1478     yc=ixer[yc].values
> 
> ValueError: too many values to unpack (expected 2)

I was able to run 

`gpf = GenePairFinder(sm,keys=keys)`

and like at the start of this whole thread, it read out

> Finding cluster-specific markers in ad:adjusted_annotations_20220408.
> ... storing 'adjusted_annotations_20220408' as categorical
> Finding cluster-specific markers in jp:annotations_20220509.
> ... storing 'annotations_20220509' as categorical

And ultimately can generate pairs of genes given annotations from my objects, as with the following code:

```
n1 = 'ad_BPC | ISL1+, LHX34+ | Parietopsin+' #cell type ID from organism 1 (must be present in `sam1.adata.obs[k1]`)
n2 = 'jp_ParapinealPR_Parietopsin+' #cell type ID from organism 2 (must be present in `sam2.adata.obs[k1]`)
Gp,G1,G2 = gpf.find_genes(n1,n2)
#Gp are the gene pairs, G1 are the genes from organism 1, G2 are the genes from organism 2

Gp[:5],G1[:5],G2[:5]
```

> (array(['ad_MSTRG.13797;jp_MSTRG.13797', 'ad_MSTRG.2759;jp_MSTRG.2759',
>         'ad_MSTRG.8987;jp_MSTRG.8987', 'ad_MSTRG.19717;jp_MSTRG.12221',
>         'ad_MSTRG.14556;jp_MSTRG.12222'], dtype='<U29'),
>  array(['ad_MSTRG.13797', 'ad_MSTRG.2759', 'ad_MSTRG.8987',
>         'ad_MSTRG.19717', 'ad_MSTRG.14556'], dtype='<U14'),
>  array(['jp_MSTRG.13797', 'jp_MSTRG.2759', 'jp_MSTRG.8987',
>         'jp_MSTRG.12221', 'jp_MSTRG.12222'], dtype='<U14'))

However, it was not able to complete 

`gene_pairs = gpf.find_all(align_thr=0.05)`

, giving the same problem as earlier, "ValueError: too many values to unpack (expected 2)"



[levels_ad.txt](https://github.com/atarashansky/SAMap/files/8684774/levels_ad.txt)
[levels_jp.txt](https://github.com/atarashansky/SAMap/files/8684
[results_of_key=none.txt](https://github.com/atarashansky/SAMap/files/8684841/results_of_key.none.txt)
775/levels_jp.txt)

**Comment by philoel** [comment]
[levels_jp.txt](https://github.com/atarashansky/SAMap/files/8754134/levels_jp.txt)
Hey Alex, sorry I just realized the levels_jp.txt seems not to have uploaded correctly.

**Comment by philoel** [comment]
As a bit of an update, I managed to get the same two objects to SAMap together and make Sankey plots and heatmaps and the Mapping Table, using an older installation of SAMap (v0.3.4) that I had installed in a different conda environment. I can't get the genepairfinder tool to work in the older version, but it does work in 1.0.2 if I manually query two cell types. 

So I guess from this I infer that the datasets are capable of going through the code, they are just hitching on something in 1.0.2?

**Comment by philoel** [comment]
Hi Alec, I'm hoping you can share the hunch you were suspecting, so that I can sit down with my local python guy and maybe make some progress on this. 

Since the example dataset worked well with SAMap in my hands, and since it worked with different species' datasets, I guess the software is fine but I am at a loss for what to edit on my .h5ad object, to make it compatible with SAMap. I prepare all the .h5ad objects with the same code from Seurat objects in R, so I am not sure where to look next.

It's a bit of a bottleneck for whether I use SAMap results in the manuscript. Any tips much appreciated!

Best,
Phil

**Comment by atarashansky** [comment]
Can you replace all special character separators (e.g. " | ", "/", etc) with an underscore "_" and try again?

**Comment by atarashansky** [comment]
Ahh, I'm so sorry about this. I think semicolons are a reserved character with the way I have things set up.

The internal logic is encoding edges between cell types by concatenating their labels with ";" --> "sp1_celltype1;sp2_celltype2" corresponds to an edge. It then splits up these strings by ";" to get the cell type labels encoded in those edges for further processing. So if you have a label like `sp1_celltype1;description`, it'll give an edge that looks like "sp1_celltype1;description;sp2_celltype2, and then the string parsing breaks. 

None of this was documented, of course, and I'm sorry it's been causing you so much trouble! 

I think if you replace semicolons with another character in all your labels, the problem should be resolved. In the meantime, I will work on re-implementing so that this doesn't occur in the future (probably by concatenating with a string that is extremely unlikely to appear in the wild, e.g. `;;@@;;`.

Let me know if this still doesn't fix your issue....

**Comment by philoel** [comment]
Hi Alec!

You did it! That was the cause. It's working great now. 

To recap for anyone reading through in the future, my annotations were very detailed, usually involving a hierarchy of annotations for example "neuron | type_of_neuron | marker" and "muscle | axial | marker", that sort of thing. I was using the | character to separate the annotation types, and also had a semicolon in there too in some cases, for example when I thought I might have doublet of neuron;muscle . 

Alec had me replace all special character separators (e.g. " | ", "/", and ";") with an underscore "_"; I used a double underscore so that I could separate the fields again later in any document that is generated from SAMap.
