### ISSUE TITLE
Where can I download fasta data of transcriptome/proteome for different species?

### ISSUE THREAD

**Issue by Smilenone** [atarashansky/SAMap#81]
Hi,

I would like to use SAMap on different species and use blast to align genes from different species. But where can I download fasta data of transcriptome/proteome for different species?

**Comment by atarashansky** [comment]
The way I handle isoforms is to sum up the counts of the various isoforms into one gene symbol. I keep the isoforms separate in the fasta file and use this parameter to collapse their homologies into one node in the homology graph:
https://github.com/atarashansky/SAMap/blob/f2f1a5b4324f81dc9b7c65f98b980d447f66b629/samap/mapping.py#L50-L61

So, for example, for a particular species you could pass in a list of tuples that look like:
[(Gene A, Gene A), (Gene B, Gene B), (Gene C.1, Gene C), (Gene C.2, Gene C), (Gene C.3, Gene C), ...] 
Here, the three isoforms of Gene C (1, 2, and 3) are going to collapse down to a single node corresponding to Gene C in the homology graph used by SAMAP.

**Comment by dariotommasini** [comment]
Hi @atarashansky , 

I am using the names parameter to collapse different isoforms for the same gene. However, this step is really slow when using many species, in my case, 6. Is there any way to save the initial homology graph, and then reuse it for a different SAMap run (with the same species)? Would it be the gnnm parameter in SAMAP or does that expect an already refined homology graph? Thanks!

**Comment by atarashansky** [comment]
It would be with the gnnm parameter!

**Comment by dariotommasini** [comment]
Thanks! So it wants a tuple with three elements: (sparse adjacency matrix, numpy array of genes, dictionary of species-specific genes)

 I understand the first two elements, what is the third element? 

It would look something like this, right? 

```
sm2 = SAMAP(sams, gnnm = (sm.gnnm, sm.gns, ?) )
```

**Comment by atarashansky** [comment]
I think it would be the equivalent of `sm.gns_dict`

I appreciate you enduring my awful variable naming conventions :D
