### ISSUE TITLE
Feature Request: p-values for the gene:gene pairs in genepairfinder:find_all()

### ISSUE THREAD

**Issue by philoel** [atarashansky/SAMap#86]
I'm trying to take the list of gene pairs produced with

```
gene_pairs = gpf.find_all(align_thr=0.05)
```

, as input for some GO term enrichment work I'm doing separately in R (where I am a bit more comfortable). However, for this we need the p-values or other score that was computed for the gene pairs. 

I see in the analysis.py that these are computed and then the results are simply filtered of pairs that don't meet a threshold, but I don't know how to edit the code to leave in the p-values, or some sort of score. 

I see that the structure of the gene_pairs object is columns where each column name is the cell-cell pair, and the entries under that are the gene-gene pairs. I guess it would be practical to have a second column for each original column, carrying the p-value, even though this would double the width of the outputted column.

**Comment by atarashansky** [comment]
`pip install samap=1.0.3`

Pvalues are now added to the table.

**Comment by philoel** [comment]
Awesome, thanks for adding. I see there are two columns of p-values, pval1 and pval2. What do these correspond do? I guess maybe raw and adjusted. Can you describe that a bit more?

**Comment by atarashansky** [comment]
pvals1 = pvalues for genes in species 1, pvals2 = pvalues for genes in species 2
