### ISSUE TITLE
samalg can't import.

### ISSUE THREAD

**Issue by Ray569743422** [atarashansky/SAMap#88]
Traceback (most recent call last):
  File "/dellfsqd2/ST_OCEAN/USER/wangrui21/03.software/SAMap/samap/mapping.py", line 9, in <module>
    from samalg import SAM
ModuleNotFoundError: No module named 'samalg'

When I execut "python samap/mapping.py", I meet this error.  How to fix it?

**Comment by atarashansky** [comment]
Please look at the vignette for example on how to use:
https://github.com/atarashansky/SAMap/blob/main/SAMap_vignette.ipynb

`samap/mapping.py` is not runnable from the command line.

**Comment by DinithiRajapaksha** [comment]
---------------------------------------------------------------------------
Hi,
I get the following error. I have installed SAMap following the vignette. Can you please help me to resolve this issue



ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from samap.mapping import SAMAP
      2 from samap.analysis import (get_mapping_scores, GenePairFinder,
      3                             sankey_plot, chord_plot, CellTypeTriangles, 
      4                             ParalogSubstitutions, FunctionalEnrichment,
      5                             convert_eggnog_to_homologs, GeneTriangles)
      6 from samalg import SAM

File ~\samap_directory\samap\__init__.py:4
      2 import scipy as sp
      3 import numpy as np
----> 4 import samalg.utilities as ut
      5 import warnings
      6 import scanpy as sc

ModuleNotFoundError: No module named 'samalg'

**Comment by atarashansky** [comment]
Can you run `pip install sam-algorithm` and try again?
