### ISSUE TITLE
input formats?

### ISSUE THREAD

**Issue by gulfshores** [atarashansky/SAMap#89]
Hi, 
I'm trying to compare a couple of species/datasets with SAMap. I've worked through a bunch of errors about the lack of parameters and formats in the input data. However, now I'm getting: 
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')
AttributeError: 'matrix' object has no attribute 'multiply'
I've checked the ingoing matrices for these things and with different types on the matrices. What are they supposed to be? How did you pre process your datasets before samap (before what's in the notebook)? 

Also  I have figured out where you are supposed to get them from?! Mainly adata.var["weights"] and sam1.adata.uns["run_args"]. Where do these weight some from? 

Hope you have the time to help! 
Max (Quake group)

**Comment by atarashansky** [comment]
Not sure about your error yet since I haven't seen the code or stacktrace, but try installing samap v1.0.4 (`pip install samap==1.0.4`) and see if that fixes your issue.
