### ISSUE TITLE
Is SAMap suitable for plant scRNA-seq?

### ISSUE THREAD

**Issue by SCQUchenyang** [atarashansky/SAMap#90]
Dear Sir,
I am wondering whether SAMap is applicable to plant scRNA-seq data? 
Chenyang

**Comment by atarashansky** [comment]
Hi Chenyang!

It has not been applied to plant scRNA-seq data, but there's no reason why it shouldn't work :) As long as you can BLAST two plant transcriptomes against each other, then the method should work. If you run into any issues, please let me know. I'd be more than happy to set up a meeting to try and get it working on plant data!!

Best,
Alec

**Comment by SCQUchenyang** [comment]
> Hi Chenyang!
> 
> It has not been applied to plant scRNA-seq data, but there's no reason why it shouldn't work :) As long as you can BLAST two plant transcriptomes against each other, then SAMap should work. If you run into any issues, please let me know. I'd be more than happy to set up a meeting to try and get it working on plant data!!
> 
> Best, Alec
hey,
Alec, I am doing something to test SAMap on plant. But now  I met an error 
"Length of passed value for var_names is 2000, but this AnnData has shape: (12094, 26074)".
Does this mean that my h5ad file is inappropriate？My h5ad files are saved through “SaveH5Seurat” and "Convert" using a Seurat object.
Best,
Chenyang

**Comment by atarashansky** [comment]
Can you give me more context? What code were you trying to run when you encountered this error?

**Comment by SCQUchenyang** [comment]
hey,
Alec, I'm glad to tell you that I have successfully applied SAMap to plants. And the error “Length of passed value for var_names is 2000, but this AnnData has shape: (12094, 26074)” was due to that the h5ad data contains "variable features". Before saving a seurat_object to h5ad, "seurat_object @assays$RNA@var.features" and "seurat_object @assays$RNA@scale.data" needs to be cleared. I hope this will be useful to others.
Now I have another difficulty. I am trying to display a sankey plot for my species and I run "sankey_plot ( MappingTable ,  align_thr = 0.05 ,  species_order  =  [ 'species1' , 'species2' , 'species3' ])" .
But I didn't get any plot. Is there any command for me to save the sankey_plot  to a pdf？
Best,
Chenyang

**Comment by atarashansky** [comment]
Hi chenyang! Glad to see that it's working so far...

Are you running the sankey_plot function in a Jupyter notebook? It should display in the cell you run it in.

In any case, try the following:
```
import holoviews as hv
plot = sankey_plot(...)
hv.save(plot, 'sankey_plot.png', fmt='png')
# not sure if pdf will work, but you can try:
# hv.save(plot, 'sankey_plot.pdf', fmt='pdf')
```

**Comment by atarashansky** [comment]
Closing for now, please reopen if you have any more issues.
