### ISSUE TITLE
Error in running map_genes.sh

### ISSUE THREAD

**Issue by djlmt** [atarashansky/SAMap#92]
Hi there - trying to run the SAMap on my samples but encountered the following error. Any thoughts? Thanks in advance.

Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 194 sequences in 51.5975 seconds.
Running tblastx in both directions
../../map_genes.sh: line 124: 2718942 Killed                  tblastx -query $tr1 -db $tr2 -outfmt 6 -out "maps/${n1}${n2}/${n1}_to_${n2}.txt" -num_threads ${n_threads} -max_hsps 1 -evalue 1e-6
../../map_genes.sh: line 124: 2719746 Segmentation fault      (core dumped) tblastx -query $tr2 -db $tr1 -outfmt 6 -out "maps/${n1}${n2}/${n2}_to_${n1}.txt" -num_threads ${n_threads} -max_hsps 1 -evalue 1e-6

**Comment by atarashansky** [comment]
It's hard to know why it's segfaulting from the above logs. This seems to be a problem with BLAST.

Can you tell me more about your fasta files? Are they nucleotide sequences? Are the files properly formatted?

**Comment by atarashansky** [comment]
Closing for now - please reopen if this issue is still relevant.
