### ISSUE TITLE
0 `mo` gene symbols match between the datasets and the BLAST graph.

### ISSUE THREAD

**Issue by houruiyan** [atarashansky/SAMap#97]
Hello, thank you very much for your kind help. 

I meet another question again. Now I can smoothly run the SAMP(). However, the result cannot meet my exception. I always get the 0 gene symbols match between the datasets and the BLAST graph.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/56068158/209159231-2ad39c81-bee5-4cb7-a9bb-a9bb17331ea1.png">

The following is my code
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/56068158/209159499-5bdf0d15-bba2-4bc2-b6eb-c4cd4aab016e.png">
<img width="970" alt="image" src="https://user-images.githubusercontent.com/56068158/209159555-1fb1af75-bbdc-40e8-9e6c-1430dec77e5e.png">
<img width="923" alt="image" src="https://user-images.githubusercontent.com/56068158/209159621-a5a0cddf-3922-43d2-9742-6df493aba597.png">

Hope to get yoru answer. Thank you very much!

**Comment by atarashansky** [comment]
Hi @houruiyan ! Notice how in the transcriptomes, you have the isoforms! ("ENSG.....1234**.1**"), whereas in your data you do not have the isoform. So the strings don't match up.

What I would recommend is to read the mapping tables (e.g. `mo_to_ra.txt`) and delete the `.1/.2/.3`s at the end of all the gene names, then save the tables. That should fix your problem.

Best,
Alec

**Comment by houruiyan** [comment]
Thank you very much. Alec! 
Maybe it is not correct to just delete `.1 .2 .3` ? The different isoform has different value in that mapping table.　So which isoform's value should I select for the certain gene? Hope to hear you. Thank you!

**Comment by atarashansky** [comment]
It's okay to delete `.1 .2 .3` as SAMap will just collapse all isoforms into one node for that transcript and combine all the different mapping values.

So if `A_GENE1.1` maps to `B_GENE1` and `A_GENE1.2` maps to `B_GENE2`, then `A_GENE1` will map to `B_GENE1` _and_ `B_GENE2`.

**Comment by atarashansky** [comment]
Closing for now! Please reopen if you're still having trouble.
