### ISSUE TITLE
Problem with Gp,G1,G2 = gpf.find_genes(n1,n2)

### ISSUE THREAD

**Issue by JoshuaNguyen123** [atarashansky/SAMap#98]
Hi Alec, 

Here is my current problem and do not understand why this is happening. 

Thanks, 

Josh

![image](https://user-images.githubusercontent.com/83887245/209415001-d804fe07-b64b-4970-b3fe-9e6af494a9e2.png)

**Comment by atarashansky** [comment]
Hi @JoshuaNguyen123! Thanks for catching this, I made a change recently and forgot to update the tutorial notebook. Please take a look at the most up-to-date version on Github, it should work now.
