### ISSUE TITLE
"Too many values to unpack" ENRICHMENT_SCORES,NUM_ENRICHED_GENES,ENRICHED_GENES = FE.calculate_enrichment(verbose=True)

### ISSUE THREAD

**Issue by JoshuaNguyen123** [atarashansky/SAMap#99]
Alec, 

I am having some problems with this section. I have attached the issue. 

![image](https://user-images.githubusercontent.com/83887245/209415430-4ba1c008-8615-4b46-82c2-7b6fcf4702a0.png)

![image](https://user-images.githubusercontent.com/83887245/209415446-a03b89c4-127b-4916-b00f-c8b4ec099685.png)

Thank you very much for your help!

**Comment by atarashansky** [comment]
For context, this particular functionality has not been maintained and is most likely very outdated. I've been meaning to remove it from the tutorial notebook. It was primarily meant for use to generate a couple figures in the original publication. Regardless, I'll do my best to see if we can get it working for you!

This one is a bit hard to debug without knowing more information. After cell [130] fails, can you print out `FE.DICT` and show me the output? Also, while you're at it, please show me: 
`FE.GENE_SETS` and `FE.RES`.

**Comment by atarashansky** [comment]
Thanks for identifying this bug! I am able to reproduce it using the example data and will post back when it's fixed!

**Comment by atarashansky** [comment]
Hi @JoshuaNguyen123, update to the latest version `pip install samap==1.0.10` and try again! The issue should be resolved. 

Please reopen this issue if you're still having trouble!
